# Generated by Django 6.0.6 on 2026-07-04 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_order_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_best_seller',
            field=models.BooleanField(default=False, help_text="Home page ke 'Best Sellers' section mein dikhega"),
        ),
        migrations.AddField(
            model_name='product',
            name='is_deal_of_day',
            field=models.BooleanField(default=False, help_text="Home page ke 'Deal of the Day' section mein dikhega"),
        ),
        migrations.AddField(
            model_name='product',
            name='is_new_arrival',
            field=models.BooleanField(default=False, help_text="Home page ke 'New Arrivals' section mein dikhega"),
        ),
        migrations.AddField(
            model_name='product',
            name='is_top_rated',
            field=models.BooleanField(default=False, help_text="Home page ke 'Top Rated' section mein dikhega"),
        ),
        migrations.AddField(
            model_name='product',
            name='is_trending',
            field=models.BooleanField(default=False, help_text="Home page ke 'Trending' section mein dikhega"),
        ),
        migrations.AddField(
            model_name='product',
            name='old_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Discount se pehle wala price (optional). Khali chor sakte ho.', max_digits=10, null=True),
        ),
    ]
